import { createElement } from "@lwc/engine-dom";
import ImportProjectRecentComponent from "c/importProjectRecentComponent";

describe("c-import-project-recent-component", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-import-project-recent-component", {
      is: ImportProjectRecentComponent
    });

    // Act
    document.body.appendChild(element);

    // Assert
    const div = element.shadowRoot.querySelector(".recent-title");
    expect(div).not.toBeNull();
  });
});
