name: AppExchange CI/CD

on:
  push:
    branches: [develop, main, "release/*"]
  pull_request:
    branches: [develop, main, "release/*"]
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Exécuter les tests unitaires ?"
        required: false
        default: "true"

env:
  NODE_VERSION: "18"

jobs:
  # 0. Validation préalable (sans environnement Salesforce)
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run lint
      - name: Run unit tests
        if: ${{ github.event.inputs.run_tests == 'true' || github.event_name != 'workflow_dispatch' }}
        run: npm run test:unit:coverage
      - run: npm run prettier:verify
      - name: Validation des métadonnées Salesforce
        run: |
          echo "📋 Validation des métadonnées..."
          npm install -g @salesforce/cli
          # Validation de la structure du projet
          sf project validate --source-dir force-app
          # Validation de la syntaxe Apex (si possible)
          sf apex run --source-dir force-app --check-only
      - name: Validation des dépendances
        run: |
          echo "🔗 Vérification des dépendances..."
          # Vérification des références entre composants
          sf project retrieve start --source-dir force-app --check-only

  # 1. Integration Testing in Dedicated Sandbox (feature/develop branches)
  integration:
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run lint
      - name: Run unit tests
        if: ${{ github.event.inputs.run_tests == 'true' || github.event_name != 'workflow_dispatch' }}
        run: npm run test:unit:coverage
      - run: npm run prettier:verify
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli
      - name: Authenticate to Integration Sandbox
        run: |
          printf "%s" "${{ secrets.SF_JWT_KEY_FILE }}" > jwt.key
          sf org login jwt --client-id ${{ secrets.SF_CONNECTED_APP_CONSUMER_KEY }} --jwt-key-file jwt.key --username ${{ secrets.SF_INT_USERNAME }} --instance-url ${{ secrets.SF_INT_INSTANCE_URL }} --alias int-sandbox
      - name: Deploy & Test in Integration Sandbox
        run: |
          sf project deploy start --source-dir force-app --target-org int-sandbox
          sf apex run test --test-level RunLocalTests --target-org int-sandbox --wait 10
      - run: rm -f jwt.key
# ... existing code ...
